### ISSUE TITLE
Creating User stories

### ISSUE THREAD

**Issue by EXC3ll3NTrhyTHM** [Advanced-Software-Engineering-UMKC/Nine-Mens-Morris#1]
Using the template discussed in class. Should include estimated efforts. Entire team should perform the planning poker
approach to the effort estimation.
- Choosing player’s turn
- Setting up a game
- Placing a piece
- Moving a piece
- Flying a piece
- Removing an opponent’s piece
- Determining if the game is over
- Recording all moves of a game in a text file
- Replaying a game recorded in a text file manually
- Replaying a game recorded in a text file automatically (with a configurable time delay
between two moves)

**Comment by suryansh-max** [comment]
User Stories
Choosing Player’s Turn

As a player, I want the system to identify which player's turn it is so that I can know when it's my turn to play without confusion.
Estimated Effort: [Effort estimate]
Setting Up a Game

As a game developer, I want to set up a game so that players can start a new session with the necessary configurations.
Estimated Effort: [Effort estimate]
Placing a Piece

As a player, I want to place a game piece on the board so that I can start playing the game with proper validation rules enforced.
Estimated Effort: [Effort estimate]
Moving a Piece

As a player, I want to move my piece on the board so that I can play the game according to its movement rules and strategy.
Estimated Effort: [Effort estimate]
Flying a Piece

As a player, I want to fly my piece across the board under specific game conditions so that I can utilize advanced moves and strategy when the game allows it.
Estimated Effort: [Effort estimate]
Removing an Opponent’s Piece

As a player, I want to remove an opponent's piece from the board when allowed so that I can gain a strategic advantage.
Estimated Effort: [Effort estimate]
Determining if the Game is Over

As a player, I want the system to determine if the game is over so that I can see the final result and know when to end the session.
Estimated Effort: [Effort estimate]
Recording All Moves of a Game in a Text File

As a player, I want all moves of the game recorded in a text file so that I can review or analyze the game later.
Estimated Effort: [Effort estimate]
Replaying a Game Recorded in a Text File Manually

As a player, I want to manually replay a game recorded in a text file so that I can go through the moves at my own pace.
Estimated Effort: [Effort estimate]
Replaying a Game Recorded in a Text File Automatically

As a player, I want to automatically replay a game recorded in a text file with a configurable time delay between moves so that I can observe the game flow easily.
Estimated Effort: [Effort estimate]


this is generated by chatgpt i will cross check and update if its required

will create Estimate by poker

**Comment by EXC3ll3NTrhyTHM** [comment]
Revised user stories: 1 day = 3 hours | total: 54 hrs

Setting Up a Game Board
As a player, I want to be able to start a new game on an empty board.
Estimate: 2 days

Placing a Piece
As a player, I want to be able to place my pieces on the board so that I can complete my turn.
Estimate: 1 day

Turn Indication - have separate class tracking the turn, Game Manager
As a player, I want to know when it’s my turn so that I can play on my turns.
Estimate: 1 day

Moving a Piece
As a player with all my pieces placed, I want to be able to move one of my pieces to an empty intersection so that I can complete my turn.
Estimate: 1 day

Removing an Opponent’s Piece
As a player with a newly created mill, I want to be able to remove one of my opponent’s pieces.
Estimate: 2 days

Flying a Piece
As a player with exactly 3 pieces remaining, I want to be able to move one of my pieces to any empty intersection so that I can complete my turn.
Estimated Effort: 1 day

Determining if a Game is Over
As a player, I want to know if the game is over after each move.
Estimate: 1 day

Record All Moves of a Game in a Text File
As a player, I want to be able to save my game in a file so that I can replay it later.
Estimate: 1 day

Replaying a Game Recorded in a Text File
As a player, I want to replay a saved game so that I can rewatch it.
Estimate: 3 days

Swap to Other Men’s Morris Games - it’ll be important to have the function be based on the available moves and not the board
As a player, I want to be able to switch to other Men’s Morris games (6, 9, 12).
Estimate: 3 days

Web hosting
As a player, I want to be able to access the website so that I can play the game.
Estimate: 2 days
